sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vilislav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vilislav/react-test npm test

after_success:
  - docker build -t vilislav/multi-client ./client
  - docker build -t vilislav/multi-nginx ./nginx
  - docker build -t vilislav/multi-server ./server
  - docker build -t vilislav/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vilislav/multi-client
  - docker push vilislav/multi-nginx
  - docker push vilislav/multi-server
  - docker push vilislav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-024765960203"
  bucket_path: "multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  secure: $AWS_SECRET_KEY
  on:
    branch: master